### ISSUE TITLE
Getting LNK2001 error

### ISSUE THREAD

**Issue by mrzaxaryan** [sneusse/aot-static-example#1]
Hi thank you for example but it does not work for me.
Steps: Clone repo and run build.bat using developer PowerShell.
Getting: `error LNK2001: unresolved external symbol UnmanagedTest`
Tested sdk: `7.0.400` `8.0.100-preview.7.23376.3`

**Comment by JackHarckness** [comment]
How did you solve the problem?

**Comment by JackHarckness** [comment]
I've opened an issue in dotnet/docs#40680 however the problem is resolved now by starting `build.bat` from x64 Native Tools Command Prompt for VS 2022. I'm afraid there is simply something wrong with my msvc setup.
